#!/usr/bin/env python
"""Render the flat root ``.env`` from ``config/config.yml`` (the SSoT).

- **Derived values** (paths, ports, URLs, buckets, backends) come from config.yml and are
  always overwritten on render.
- **Secret slots** are written blank and are **merge-safe**: an already-filled value in an
  existing ``.env`` is preserved (so rendering never wipes a secret you entered by hand).
- **Demo defaults** (dev-only literals) live ONLY here — e.g. a local Postgres password so
  ``make up`` works without manual secret entry. Never a real secret.

Run: ``uv run python config/.env-render.py`` (or ``make render-env``).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / "config" / "config.yml"
ENV = REPO / ".env"

# Dev-only demo literals (NOT secrets — safe local defaults). Real secrets stay blank.
DEMO_DEFAULTS: dict[str, str] = {
    "OGIP_PG_PASSWORD": "ogip",  # local Postgres/Prefect backend password (compose)
}

# Secret slots — blank in the rendered .env; filled by hand or GitHub Actions secrets (ADR-0011).
SECRET_SLOTS: tuple[str, ...] = (
    "OGIP_PG_PASSWORD",
    "OGIP_S3_ACCESS_KEY_ID",
    "OGIP_S3_SECRET_ACCESS_KEY",
    "RAWG_API_KEY",
    "STEAM_API_KEY",
    "IGDB_CLIENT_ID",
    "IGDB_CLIENT_SECRET",
    # Airbyte evaluation lane (#41) — minted by `abctl local credentials`, 15-min token TTL.
    # The Terraform provider authenticates with these, never a static bearer.
    "AIRBYTE_CLIENT_ID",
    "AIRBYTE_CLIENT_SECRET",
    # PAT for airbyte/source-github. Name matches the registry descriptor's declared slot
    # (spec/sources/games/github_repos.yaml -> `slot: GITHUB_TOKEN`); renaming it here would
    # be silent drift from the SSoT. Safe in this repo: nothing in .ci/ or .github/workflows/
    # sources .env, so the blank slot cannot clobber the token Actions injects (verified).
    "GITHUB_TOKEN",
)


def _load() -> dict[str, Any]:
    data: Any = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit(f"{CONFIG} is not a YAML mapping")
    return data


def _existing_secrets() -> dict[str, str]:
    """Preserve already-filled secret values from a prior .env (merge-safe render)."""
    kept: dict[str, str] = {}
    if not ENV.is_file():
        return kept
    for line in ENV.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip()
        if key in SECRET_SLOTS and value:
            kept[key] = value
    return kept


def _derived(cfg: dict[str, Any]) -> dict[str, str]:
    platform, storage = cfg["platform"], cfg["storage"]
    pg, svc, ep = cfg["postgres"], cfg["services"], cfg["endpoints"]
    return {
        "OGIP_DATA_DIR": str(platform["data_dir"]),
        "OGIP_LOG_DIR": str(platform["log_dir"]),
        "OGIP_LOG_LEVEL": str(platform["log_level"]),
        "OGIP_LOG_JSON": str(platform["log_json"]).lower(),
        "OGIP_STORAGE_BACKEND": str(storage["backend"]),
        "OGIP_S3_ENDPOINT_URL": str(storage["endpoint_url"]),
        "OGIP_S3_RAW_BUCKET": str(storage["raw_bucket"]),
        "OGIP_S3_REGION": str(storage["region"]),
        "OGIP_PG_HOST": str(pg["host"]),
        "OGIP_PG_PORT": str(pg["port"]),
        "OGIP_PG_USER": str(pg["user"]),
        "OGIP_PG_DATABASE": str(pg["database"]),
        "POSTGRES_PORT": str(svc["postgres_port"]),
        "MINIO_API_PORT": str(svc["minio_api_port"]),
        "MINIO_CONSOLE_PORT": str(svc["minio_console_port"]),
        # Observability stack ports — the obs compose reads these (else it falls back to
        # literals that duplicate the config.yml SSoT).
        "VICTORIAMETRICS_PORT": str(svc["victoriametrics_port"]),
        "LOKI_PORT": str(svc["loki_port"]),
        "GRAFANA_PORT": str(svc["grafana_port"]),
        # NOTE: never emit bare PREFECT_* names — Prefect 3 loads .env through
        # pydantic-settings, so PREFECT_API_URL would hijack its own setting and force
        # client→server mode, breaking ephemeral runs. Ours stay OGIP_-prefixed; the
        # `server` run-profile exports PREFECT_API_URL explicitly when a server is up.
        "OGIP_PREFECT_PORT": str(svc["prefect_port"]),
        "OGIP_PREFECT_API_URL": str(ep["prefect_api_url"]),
        # Airbyte evaluation lane (#41) — experimental, off the `make` path. The port is
        # abctl's local ingress; the schema is the destination inside the shared Postgres.
        "OGIP_AIRBYTE_PORT": str(svc["airbyte_port"]),
        "OGIP_AIRBYTE_SCHEMA": str(pg["airbyte_schema"]),
    }


def render() -> None:
    cfg = _load()
    kept = _existing_secrets()
    derived = _derived(cfg)

    lines: list[str] = [
        "# GENERATED by config/.env-render.py — DO NOT EDIT derived values.",
        "# Edit config/config.yml and re-run `make render-env`. Fill blank secrets by hand.",
        "",
        "# --- derived (from config/config.yml) ---",
    ]
    lines += [f"{k}={v}" for k, v in derived.items()]
    lines += ["", "# --- secrets (blank = unset; filled by hand / GitHub Actions secrets) ---"]
    for slot in SECRET_SLOTS:
        value = kept.get(slot, DEMO_DEFAULTS.get(slot, ""))
        lines.append(f"{slot}={value}")
    lines.append("")

    ENV.write_text("\n".join(lines), encoding="utf-8")
    print(f"rendered {ENV} ({len(derived)} derived, {len(SECRET_SLOTS)} secret slots)")


if __name__ == "__main__":
    render()
